FROM postgres:16.0-alpine3.18

ENV VERSION=1.0.2
ENV POSTGRES_USER="postgres"
ENV POSTGRES_PASSWORD="postgres"
ENV POSTGRES_DB="postgres"

COPY initdb.sql /docker-entrypoint-initdb.d/initdb.sql

EXPOSE 5432